name: planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # dependências do seu projeto
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  path: ^1.9.1
  crypto: ^3.0.7
  flutter_localizations:
    sdk: flutter
  sqflite_common_ffi_web: ^1.1.2
  
  # dependência do gerador de ícones
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# configurações do ícone
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FAF0F0"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true